services:
  api:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./data:/data
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true