[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.115.12",
    "requests>=2.32.3",
    "rich>=14.0.0",
    "uvicorn>=0.34.0",
]
